# http://localhost/tutorial/image-building-best-practices/

version: "3.7"

services:

  express:
    image: node:lts-alpine
    container_name: express
    restart: always
    ports:
      - 3001:3001
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    # Bind mount local contents to container volume
    volumes:
      - ./express/:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: budgetfree
      
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: budgetfree
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  pg_data:


# docker-compose up --build
# docker-compose up
# docker-compose down --volumes
# docker-compose down