# http://localhost/tutorial/image-building-best-practices/

version: "3.7"

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: budgetfree
      PGDATA: /var/lib/postgresql/data/pgdata

  express:
    depends_on:
      - postgres
    image: node:lts-alpine
    container_name: express
    restart: always
    ports:
      - 3001:3001
    # This should match the WORKDIR in the associated Dockerfile
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    # Bind mount local contents to container volume
    volumes:
      - ./express/:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: budgetfree

  react:
    depends_on:
      - express
    build: ./react_frontend/
    container_name: react
    ports:
      - 3000:3000
    # This should match the WORKDIR in the associated Dockerfile
    working_dir: /app
    volumes:
      - ./react_frontend/:/app

volumes:
  pg_data:


# docker-compose up --build
# docker-compose up
# docker-compose down --volumes
# docker-compose down